name: "Frogbot Scan Repository"
on:
  push:
    branches: ["master"]
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
  security-events: write
  id-token: write
jobs:
  scan-repository:
    runs-on: ubuntu-latest
    environment: frogbot
    strategy:
      matrix:
        branch: ["master"]
    steps:
      - uses: jfrog/frogbot@v3
        with:
          oidc-provider-name: jackcu-github-oidc
          oidc-audience: jfrog-jackcu-solengeu
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_PROJECT: ${{ vars.JF_PROJECT }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JF_GIT_BASE_BRANCH: ${{ matrix.branch }}